language: bash

script:
  - bats test/pak_brew.bats

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats; fi
  -
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:duggan/bats --yes;
      sudo apt-get update -qq;
      sudo apt-get install -qq bats;
    fi
